spring:

  application:
    name: swiftpay-ledger

  datasource:
    url: jdbc:postgresql://postgres:5432/swiftpay
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

  kafka:

    bootstrap-servers: kafka:9092

    consumer:

      group-id: ledger-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.swiftpay.ledgerservice.event.PaymentEvent
        spring.json.use.type.headers: false

      concurrency: 3

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false
        linger.ms: 5
        compression.type: snappy

      batch-size: 16384
      buffer-memory: 33554432
      acks: 1

management:

  endpoints:

    web:

      exposure:

        include: health,info

  endpoint:

    health:

      show-details: always

server:
  port: 8081

  tomcat:
    threads:
      max: 400
      min-spare: 50

    accept-count: 200

    max-connections: 10000

logging:

  level:

    root: INFO

    com.swiftpay.ledgerservice: INFO